/**
 * Extracts ABI definitions from Foundry compiled artifacts
 * and generates TypeScript files for wagmi type inference.
 *
 * Usage: bun scripts/extract-abis.ts
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const CONTRACTS_OUT = join(import.meta.dir, "../../contracts/out");
const ABI_DIR = join(import.meta.dir, "../src/client/config/abis");

// contract name → export name mapping (avoid ugly "aI" camelCase)
const TARGET_CONTRACTS: Record<string, string> = {
  AgentRegistry: "registryAbi",
  AgentDelegation: "delegationAbi",
  RationaleCommitment: "rationaleAbi",
  CredibilityRegistry: "credibilityAbi",
  GovernorResolver: "resolverAbi",
  GovernorAgentDelegation: "govDelegationAbi",
  MockGovernor: "governorAbi",
  MockERC20Votes: "tokenAbi",
};

async function main() {
  await mkdir(ABI_DIR, { recursive: true });

  let indexExports: string[] = [];

  for (const [name, exportName] of Object.entries(TARGET_CONTRACTS)) {
    const artifactPath = join(CONTRACTS_OUT, `${name}.sol`, `${name}.json`);
    try {
      const raw = await readFile(artifactPath, "utf-8");
      const artifact = JSON.parse(raw);
      const abi = artifact.abi;

      if (!abi || !Array.isArray(abi)) {
        console.warn(`  SKIP ${name}: no ABI found`);
        continue;
      }

      const content = `// Auto-generated by extract-abis.ts — do not edit
export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;
`;
      const outPath = join(ABI_DIR, `${name}.ts`);
      await writeFile(outPath, content);
      console.log(`  OK ${name} → ${exportName} (${abi.length} entries)`);

      indexExports.push(
        `export { ${exportName} } from "./${name}";`
      );
    } catch (e: any) {
      console.error(`  ERR ${name}: ${e.message}`);
    }
  }

  // Write barrel index
  const indexContent = `// Auto-generated by extract-abis.ts — do not edit\n${indexExports.join("\n")}\n`;
  await writeFile(join(ABI_DIR, "index.ts"), indexContent);
  console.log(`\nWrote ${indexExports.length} ABI files + index.ts`);
}

main().catch(console.error);
