// Auto-generated by extract-abis.ts — do not edit
export const resolverAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_governor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "governor",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IGovernor"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolve",
    "inputs": [
      {
        "name": "credibility",
        "type": "address",
        "internalType": "contract ICredibilityRegistry"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "governorProposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "ProposalNotFinalized",
    "inputs": [
      {
        "name": "governorProposalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "currentState",
        "type": "uint8",
        "internalType": "enum IGovernor.ProposalState"
      }
    ]
  }
] as const;
