export type RiskLevel = "safe" | "caution" | "dangerous";
export type ContractCategory = "governance" | "treasury" | "staking" | "registry" | "token";

export interface FunctionParam {
  name: string;
  type: string;
  description: string;
}

export interface DaoFunction {
  name: string;
  signature: string;
  params: FunctionParam[];
  description: string;
  example: string;
  risk: RiskLevel;
  notes?: string;
}

export interface ContractGuide {
  name: string;
  address: string;
  category: ContractCategory;
  description: string;
  functions: DaoFunction[];
}

export const DAO_GUIDE: ContractGuide[] = [
  // ─── DAOCommittee ───────────────────────────────────────────────
  {
    name: "DAOCommittee",
    address: "0xDD9f0cCc044B0781289Ee318e5971b0139602C26",
    category: "governance",
    description: "Core DAO governance contract. Manages committee members, quorum, agenda lifecycle, and candidate registration.",
    functions: [
      {
        name: "setQuorum",
        signature: "setQuorum(uint256)",
        params: [{ name: "quorum", type: "uint256", description: "New quorum value (must be > maxMember/2 and <= maxMember)" }],
        description: "Sets the minimum number of votes required for agenda approval.",
        example: "Set the DAOCommittee quorum to 2",
        risk: "safe",
      },
      {
        name: "setCreateAgendaFees",
        signature: "setCreateAgendaFees(uint256)",
        params: [{ name: "fees", type: "uint256", description: "New fee amount in TON wei" }],
        description: "Sets the TON fee required to submit a new governance agenda (forwards to DAOAgendaManager).",
        example: "Set the agenda creation fee to 100 TON",
        risk: "safe",
      },
      {
        name: "setMinimumNoticePeriodSeconds",
        signature: "setMinimumNoticePeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Minimum notice period in seconds before voting starts" }],
        description: "Sets the minimum notice period for agendas before voting can begin.",
        example: "Set the minimum agenda notice period to 3 days",
        risk: "safe",
      },
      {
        name: "setMinimumVotingPeriodSeconds",
        signature: "setMinimumVotingPeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Minimum voting period in seconds" }],
        description: "Sets the minimum duration of the voting period for agendas.",
        example: "Set the minimum voting period to 2 days",
        risk: "safe",
      },
      {
        name: "setExecutingPeriodSeconds",
        signature: "setExecutingPeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Execution window duration in seconds" }],
        description: "Sets the time window during which an approved agenda can be executed.",
        example: "Set the agenda execution window to 2 days",
        risk: "safe",
      },
      {
        name: "setActivityRewardPerSecond",
        signature: "setActivityRewardPerSecond(uint256)",
        params: [{ name: "reward", type: "uint256", description: "New reward rate in wei per second" }],
        description: "Sets the activity reward rate paid to active committee members per second.",
        example: "Set the committee activity reward to 0.01 TON per second",
        risk: "safe",
      },
      {
        name: "increaseMaxMember",
        signature: "increaseMaxMember(uint256,uint256)",
        params: [
          { name: "newMaxMember", type: "uint256", description: "New maximum member count (must be > current)" },
          { name: "newQuorum", type: "uint256", description: "New quorum value" },
        ],
        description: "Increases the maximum number of committee members and adjusts quorum.",
        example: "Increase the max committee members to 5 with quorum 3",
        risk: "safe",
      },
      {
        name: "decreaseMaxMember",
        signature: "decreaseMaxMember(uint256,uint256)",
        params: [
          { name: "newMaxMember", type: "uint256", description: "New maximum member count (must be < current)" },
          { name: "newQuorum", type: "uint256", description: "New quorum value" },
        ],
        description: "Decreases the maximum number of committee members. May remove the last member slot.",
        example: "Decrease the max committee members to 3 with quorum 2",
        risk: "caution",
      },
      {
        name: "setSeigManager",
        signature: "setSeigManager(address)",
        params: [{ name: "newSeigManager", type: "address", description: "New SeigManager contract address" }],
        description: "Sets the SeigManager address used by DAOCommittee for seigniorage interactions.",
        example: "Set the DAOCommittee SeigManager to a new address",
        risk: "caution",
      },
      {
        name: "setDaoVault",
        signature: "setDaoVault(address)",
        params: [{ name: "newDaoVault", type: "address", description: "New DAOVault contract address" }],
        description: "Sets the DAOVault address where DAO treasury funds are held.",
        example: "Set the DAOVault address on DAOCommittee",
        risk: "caution",
      },
      {
        name: "setLayer2Registry",
        signature: "setLayer2Registry(address)",
        params: [{ name: "newLayer2Registry", type: "address", description: "New Layer2Registry contract address" }],
        description: "Sets the Layer2Registry address used for Layer2 operator registration.",
        example: "Set the Layer2Registry address on DAOCommittee",
        risk: "caution",
      },
      {
        name: "setAgendaManager",
        signature: "setAgendaManager(address)",
        params: [{ name: "newAgendaManager", type: "address", description: "New DAOAgendaManager contract address" }],
        description: "Sets the DAOAgendaManager address used for agenda creation and voting.",
        example: "Set the DAOAgendaManager address on DAOCommittee",
        risk: "caution",
      },
      {
        name: "setCandidateFactory",
        signature: "setCandidateFactory(address)",
        params: [{ name: "newCandidateFactory", type: "address", description: "New CandidateFactory contract address" }],
        description: "Sets the CandidateFactory address used to create new candidate contracts.",
        example: "Set the CandidateFactory address on DAOCommittee",
        risk: "caution",
      },
      {
        name: "setTon",
        signature: "setTon(address)",
        params: [{ name: "newTon", type: "address", description: "New TON token contract address" }],
        description: "Sets the TON token address used by DAOCommittee.",
        example: "Set the TON token address on DAOCommittee",
        risk: "caution",
      },
      {
        name: "setCandidatesSeigManager",
        signature: "setCandidatesSeigManager(address[],address)",
        params: [
          { name: "candidates", type: "address[]", description: "Array of candidate contract addresses" },
          { name: "seigManager", type: "address", description: "SeigManager address to set on each candidate" },
        ],
        description: "Batch-sets the SeigManager address on multiple candidate contracts.",
        example: "Set the SeigManager on all candidate contracts",
        risk: "caution",
      },
      {
        name: "setCandidatesCommittee",
        signature: "setCandidatesCommittee(address[],address)",
        params: [
          { name: "candidates", type: "address[]", description: "Array of candidate contract addresses" },
          { name: "committee", type: "address", description: "Committee address to set on each candidate" },
        ],
        description: "Batch-sets the committee address on multiple candidate contracts.",
        example: "Set the committee address on all candidate contracts",
        risk: "caution",
      },
      {
        name: "removeFromBlacklist",
        signature: "removeFromBlacklist(address)",
        params: [{ name: "candidate", type: "address", description: "Candidate address to remove from blacklist" }],
        description: "Removes a candidate from the governance blacklist, restoring their eligibility.",
        example: "Remove a candidate from the DAOCommittee blacklist",
        risk: "caution",
      },
      {
        name: "createCandidateOwner",
        signature: "createCandidateOwner(string,address)",
        params: [
          { name: "name", type: "string", description: "Display name for the candidate" },
          { name: "operator", type: "address", description: "Operator address" },
        ],
        description: "Creates a new candidate entry owned by the specified operator.",
        example: "Create a new governance candidate named 'MyNode' for an operator",
        risk: "caution",
      },
      {
        name: "registerLayer2CandidateByOwner",
        signature: "registerLayer2CandidateByOwner(address,address,string)",
        params: [
          { name: "operator", type: "address", description: "Operator address" },
          { name: "layer2", type: "address", description: "Layer2 contract address" },
          { name: "name", type: "string", description: "Display name for the Layer2 candidate" },
        ],
        description: "Registers a Layer2 as a governance candidate on behalf of the owner.",
        example: "Register a Layer2 operator as a governance candidate",
        risk: "caution",
      },
      {
        name: "setAgendaStatus",
        signature: "setAgendaStatus(uint256,uint256,uint256)",
        params: [
          { name: "agendaId", type: "uint256", description: "ID of the agenda" },
          { name: "status", type: "uint256", description: "New status value (0=NONE, 1=NOTICE, 2=VOTING, etc.)" },
          { name: "result", type: "uint256", description: "Result value" },
        ],
        description: "Directly overrides the status and result of a governance agenda.",
        example: "Override the status of agenda #42 to EXECUTED",
        risk: "dangerous",
      },
    ],
  },

  // ─── DAOVault ───────────────────────────────────────────────────
  {
    name: "DAOVault",
    address: "0x2520CD65BAa2cEEe9E6Ad6EBD3F45490C42dd303",
    category: "treasury",
    description: "DAO treasury vault. Holds TON, WTON, and ERC20 tokens. Supports approvals and claims (withdrawals).",
    functions: [
      {
        name: "setTON",
        signature: "setTON(address)",
        params: [{ name: "ton", type: "address", description: "New TON token contract address" }],
        description: "Sets the TON token address used by the vault.",
        example: "Set the TON address on DAOVault",
        risk: "caution",
      },
      {
        name: "setWTON",
        signature: "setWTON(address)",
        params: [{ name: "wton", type: "address", description: "New WTON token contract address" }],
        description: "Sets the WTON token address used by the vault.",
        example: "Set the WTON address on DAOVault",
        risk: "caution",
      },
      {
        name: "approveTON",
        signature: "approveTON(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address allowed to spend TON" },
          { name: "amount", type: "uint256", description: "Approval amount in TON wei" },
        ],
        description: "Approves a spender to transfer TON tokens from the vault.",
        example: "Approve 1000 TON spending from DAOVault for a specific address",
        risk: "caution",
      },
      {
        name: "approveWTON",
        signature: "approveWTON(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address allowed to spend WTON" },
          { name: "amount", type: "uint256", description: "Approval amount in WTON ray (27 decimals)" },
        ],
        description: "Approves a spender to transfer WTON tokens from the vault.",
        example: "Approve 1000 WTON spending from DAOVault for a specific address",
        risk: "caution",
      },
      {
        name: "approveERC20",
        signature: "approveERC20(address,address,uint256)",
        params: [
          { name: "token", type: "address", description: "ERC20 token contract address" },
          { name: "spender", type: "address", description: "Address allowed to spend tokens" },
          { name: "amount", type: "uint256", description: "Approval amount" },
        ],
        description: "Approves a spender to transfer any ERC20 token held by the vault.",
        example: "Approve spending of an ERC20 token from DAOVault",
        risk: "caution",
      },
      {
        name: "claimTON",
        signature: "claimTON(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount of TON in wei" },
        ],
        description: "Transfers TON from the DAO vault to a recipient. Withdraws treasury funds.",
        example: "Transfer 500 TON from DAOVault to a recipient address",
        risk: "dangerous",
      },
      {
        name: "claimWTON",
        signature: "claimWTON(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount of WTON in ray" },
        ],
        description: "Transfers WTON from the DAO vault to a recipient. Withdraws treasury funds.",
        example: "Transfer 500 WTON from DAOVault to a recipient address",
        risk: "dangerous",
      },
      {
        name: "claimERC20",
        signature: "claimERC20(address,address,uint256)",
        params: [
          { name: "token", type: "address", description: "ERC20 token contract address" },
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount to transfer" },
        ],
        description: "Transfers any ERC20 token from the DAO vault to a recipient.",
        example: "Transfer an ERC20 token from DAOVault to a recipient address",
        risk: "dangerous",
      },
    ],
  },

  // ─── SeigManager ────────────────────────────────────────────────
  {
    name: "SeigManager",
    address: "0x0b55a0f463b6defb81c6063973763951712d0e5f",
    category: "staking",
    description: "Seigniorage distribution engine. Controls reward rates, coinage ownership, minter/admin/operator roles, and staking parameters.",
    functions: [
      {
        name: "setDaoSeigRate",
        signature: "setDaoSeigRate(uint256)",
        params: [{ name: "rate", type: "uint256", description: "DAO seigniorage rate as ray (1e27 = 100%)" }],
        description: "Sets the percentage of seigniorage allocated to the DAO treasury.",
        example: "Set the DAO seigniorage rate to 50%",
        risk: "safe",
      },
      {
        name: "setPowerTONSeigRate",
        signature: "setPowerTONSeigRate(uint256)",
        params: [{ name: "rate", type: "uint256", description: "PowerTON seigniorage rate as ray" }],
        description: "Sets the percentage of seigniorage allocated to the PowerTON contract.",
        example: "Set the PowerTON seigniorage rate to 10%",
        risk: "safe",
      },
      {
        name: "setPseigRate",
        signature: "setPseigRate(uint256)",
        params: [{ name: "rate", type: "uint256", description: "Relative seigniorage rate as ray" }],
        description: "Sets the relative seigniorage rate that controls proportional distribution among stakers.",
        example: "Set the relative seigniorage rate to 40%",
        risk: "safe",
      },
      {
        name: "setAdjustDelay",
        signature: "setAdjustDelay(uint256)",
        params: [{ name: "delay", type: "uint256", description: "Number of blocks to delay" }],
        description: "Sets the delay period (in blocks) before operator commission rate changes take effect.",
        example: "Set the commission adjust delay to 93046 blocks (about 2 weeks)",
        risk: "safe",
      },
      {
        name: "setMinimumAmount",
        signature: "setMinimumAmount(uint256)",
        params: [{ name: "amount", type: "uint256", description: "Minimum staking amount in WTON ray" }],
        description: "Sets the minimum staking amount required to earn seigniorage.",
        example: "Set the minimum staking amount to 1000 WTON",
        risk: "safe",
      },
      {
        name: "setPowerTON",
        signature: "setPowerTON(address)",
        params: [{ name: "newPowerton", type: "address", description: "New PowerTON contract address" }],
        description: "Sets the PowerTON contract address that receives seigniorage rewards.",
        example: "Set the PowerTON address on SeigManager",
        risk: "caution",
      },
      {
        name: "setDao",
        signature: "setDao(address)",
        params: [{ name: "newDao", type: "address", description: "New DAO contract address" }],
        description: "Sets the DAO address that receives seigniorage rewards.",
        example: "Set the DAO address on SeigManager",
        risk: "caution",
      },
      {
        name: "setCoinageFactory",
        signature: "setCoinageFactory(address)",
        params: [{ name: "newFactory", type: "address", description: "New coinage factory address" }],
        description: "Sets the factory contract used to deploy new coinage tokens for Layer2 operators.",
        example: "Set the coinage factory address on SeigManager",
        risk: "caution",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on SeigManager to the specified address.",
        example: "Add an admin to SeigManager",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Due to renounceRole pattern, can only remove the caller itself.",
        example: "Remove the DAO's own admin role on SeigManager",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "addMinter",
        signature: "addMinter(address)",
        params: [{ name: "account", type: "address", description: "Address to grant minter role" }],
        description: "Grants the minter role on SeigManager to the specified address.",
        example: "Add a minter to SeigManager",
        risk: "caution",
      },
      {
        name: "removeMinter",
        signature: "removeMinter(address)",
        params: [{ name: "account", type: "address", description: "Address to remove minter role from" }],
        description: "Removes the minter role. Same renounceRole limitation as removeAdmin.",
        example: "Remove the DAO's own minter role on SeigManager",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "addOperator",
        signature: "addOperator(address)",
        params: [{ name: "account", type: "address", description: "Address to grant operator role" }],
        description: "Grants the operator role on SeigManager to the specified address.",
        example: "Add an operator to SeigManager",
        risk: "caution",
      },
      {
        name: "removeOperator",
        signature: "removeOperator(address)",
        params: [{ name: "account", type: "address", description: "Address to remove operator role from" }],
        description: "Removes the operator role. Same renounceRole limitation.",
        example: "Remove the DAO's own operator role on SeigManager",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "addChallenger",
        signature: "addChallenger(address)",
        params: [{ name: "account", type: "address", description: "Address to grant challenger role" }],
        description: "Grants the challenger role on SeigManager. DAO does NOT have permission -- this call reverts.",
        example: "Add a challenger to SeigManager",
        risk: "caution",
        notes: "DAO lacks permission; call will revert",
      },
      {
        name: "removeChallenger",
        signature: "removeChallenger(address)",
        params: [{ name: "account", type: "address", description: "Address to remove challenger role from" }],
        description: "Removes the challenger role on SeigManager. DAO does NOT have permission -- this call reverts.",
        example: "Remove a challenger from SeigManager",
        risk: "caution",
        notes: "DAO lacks permission; call will revert",
      },
      {
        name: "setData",
        signature: "setData(address,address,uint256,uint256,uint256,uint256,uint256)",
        params: [
          { name: "powerton", type: "address", description: "PowerTON contract address" },
          { name: "dao", type: "address", description: "DAO address" },
          { name: "powerTONSeigRate", type: "uint256", description: "PowerTON seigniorage rate (ray)" },
          { name: "daoSeigRate", type: "uint256", description: "DAO seigniorage rate (ray)" },
          { name: "relativeSeigRate", type: "uint256", description: "Relative seigniorage rate (ray)" },
          { name: "adjustCommissionDelay", type: "uint256", description: "Blocks before commission changes apply" },
          { name: "minimumAmount", type: "uint256", description: "Minimum staking amount" },
        ],
        description: "Batch-sets all core SeigManager configuration parameters in a single call.",
        example: "Set all SeigManager parameters at once (rates, delays, minimum amount)",
        risk: "dangerous",
      },
      {
        name: "setSeigStartBlock",
        signature: "setSeigStartBlock(uint256)",
        params: [{ name: "blockNumber", type: "uint256", description: "Block number at which seigniorage starts" }],
        description: "Sets the starting block number for seigniorage calculation. Alters all future seigniorage math.",
        example: "Set the seigniorage start block number",
        risk: "dangerous",
      },
      {
        name: "setInitialTotalSupply",
        signature: "setInitialTotalSupply(uint256)",
        params: [{ name: "supply", type: "uint256", description: "Initial total supply value" }],
        description: "Sets the initial total supply baseline for seigniorage calculation.",
        example: "Set the initial total supply for seigniorage formula",
        risk: "dangerous",
      },
      {
        name: "setBurntAmountAtDAO",
        signature: "setBurntAmountAtDAO(uint256)",
        params: [{ name: "amount", type: "uint256", description: "Amount of TON treated as burnt by the DAO" }],
        description: "Sets the burnt amount at DAO, used in the seigniorage formula to adjust effective total supply.",
        example: "Set the burnt amount at DAO for seigniorage calculation",
        risk: "dangerous",
      },
      {
        name: "transferCoinageOwnership",
        signature: "transferCoinageOwnership(address,address[])",
        params: [
          { name: "newSeigManager", type: "address", description: "New SeigManager that will own the coinages" },
          { name: "coinages", type: "address[]", description: "Array of coinage token addresses to transfer" },
        ],
        description: "Transfers ownership of coinage tokens to a new SeigManager. Used during SeigManager migration.",
        example: "Transfer coinage ownership to a new SeigManager during migration",
        risk: "dangerous",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on SeigManager to another address",
        risk: "dangerous",
      },
      {
        name: "renounceWTONMinter",
        signature: "renounceWTONMinter()",
        params: [],
        description: "Permanently renounces the SeigManager's minter role on WTON. IRREVERSIBLE.",
        example: "Renounce SeigManager's WTON minter role (irreversible)",
        risk: "dangerous",
        notes: "IRREVERSIBLE: SeigManager can never mint WTON seigniorage again",
      },
      {
        name: "renounceMinter",
        signature: "renounceMinter(address)",
        params: [{ name: "target", type: "address", description: "Contract on which to renounce the minter role" }],
        description: "Permanently removes SeigManager's minter role on the target contract.",
        example: "Renounce SeigManager's minter role on a target contract",
        risk: "dangerous",
        notes: "IRREVERSIBLE",
      },
      {
        name: "renouncePauser",
        signature: "renouncePauser(address)",
        params: [{ name: "target", type: "address", description: "Contract on which to renounce the pauser role" }],
        description: "Permanently removes SeigManager's pauser role on the target contract.",
        example: "Renounce SeigManager's pauser role on a target contract",
        risk: "dangerous",
        notes: "IRREVERSIBLE",
      },
      {
        name: "renounceOwnership",
        signature: "renounceOwnership(address)",
        params: [{ name: "target", type: "address", description: "Contract on which to renounce ownership" }],
        description: "Permanently abandons ownership of the target contract via SeigManager.",
        example: "Renounce SeigManager's ownership of a target contract",
        risk: "dangerous",
        notes: "IRREVERSIBLE",
      },
      {
        name: "transferOwnership",
        signature: "transferOwnership(address,address)",
        params: [
          { name: "target", type: "address", description: "Contract whose ownership is being transferred" },
          { name: "newOwner", type: "address", description: "New owner address" },
        ],
        description: "Transfers ownership of a target contract via SeigManager.",
        example: "Transfer ownership of a contract via SeigManager",
        risk: "dangerous",
      },
    ],
  },

  // ─── DAOAgendaManager ──────────────────────────────────────────
  {
    name: "DAOAgendaManager",
    address: "0xcD4421d082752f363E1687544a09d5112cD4f484",
    category: "governance",
    description: "Manages agenda lifecycle: creation, voting, execution periods, and fee settings.",
    functions: [
      {
        name: "setCreateAgendaFees",
        signature: "setCreateAgendaFees(uint256)",
        params: [{ name: "fees", type: "uint256", description: "New fee amount in TON wei" }],
        description: "Sets the TON fee required to create a new governance agenda.",
        example: "Set the agenda creation fee to 100 TON on DAOAgendaManager",
        risk: "safe",
      },
      {
        name: "setMinimumNoticePeriodSeconds",
        signature: "setMinimumNoticePeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Minimum notice period in seconds" }],
        description: "Sets the minimum notice period before voting starts on a new agenda.",
        example: "Set the notice period to 3 days on DAOAgendaManager",
        risk: "safe",
      },
      {
        name: "setMinimumVotingPeriodSeconds",
        signature: "setMinimumVotingPeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Minimum voting duration in seconds" }],
        description: "Sets the minimum duration of the voting period for agendas.",
        example: "Set the voting period to 2 days on DAOAgendaManager",
        risk: "safe",
      },
      {
        name: "setExecutingPeriodSeconds",
        signature: "setExecutingPeriodSeconds(uint256)",
        params: [{ name: "period", type: "uint256", description: "Execution window in seconds" }],
        description: "Sets the time window during which an approved agenda can be executed.",
        example: "Set the execution window to 2 days on DAOAgendaManager",
        risk: "safe",
      },
      {
        name: "castVote",
        signature: "castVote(uint256,uint256,uint256)",
        params: [
          { name: "agendaId", type: "uint256", description: "ID of the agenda" },
          { name: "voterIndex", type: "uint256", description: "Index of the committee member voting" },
          { name: "vote", type: "uint256", description: "Vote value (1=YES, 2=NO, 3=ABSTAIN)" },
        ],
        description: "Casts a vote on an active agenda on behalf of a committee member.",
        example: "Cast a YES vote on agenda #42 for committee member index 0",
        risk: "safe",
      },
      {
        name: "setCommittee",
        signature: "setCommittee(address)",
        params: [{ name: "committee", type: "address", description: "New DAOCommittee address" }],
        description: "Sets the committee address that has authority over agenda lifecycle.",
        example: "Set the committee address on DAOAgendaManager",
        risk: "caution",
      },
      {
        name: "newAgenda",
        signature: "newAgenda(address[],uint128,uint128,bool,bytes[])",
        params: [
          { name: "targets", type: "address[]", description: "Target contract addresses" },
          { name: "noticePeriodSeconds", type: "uint128", description: "Notice period" },
          { name: "votingPeriodSeconds", type: "uint128", description: "Voting period" },
          { name: "atomicExecute", type: "bool", description: "Whether all targets execute atomically" },
          { name: "bytecodes", type: "bytes[]", description: "Encoded calldata for each target" },
        ],
        description: "Creates a new governance agenda. Only callable by the committee.",
        example: "Create a new DAO agenda with targets and calldata",
        risk: "caution",
      },
      {
        name: "setExecutedAgenda",
        signature: "setExecutedAgenda(uint256)",
        params: [{ name: "agendaId", type: "uint256", description: "ID of the agenda" }],
        description: "Marks an agenda as executed after its calldata has been run.",
        example: "Mark agenda #42 as executed",
        risk: "caution",
      },
      {
        name: "endAgendaVoting",
        signature: "endAgendaVoting(uint256)",
        params: [{ name: "agendaId", type: "uint256", description: "ID of the agenda" }],
        description: "Ends the voting period for an agenda and finalizes the vote result.",
        example: "End voting on agenda #42",
        risk: "caution",
      },
      {
        name: "setResult",
        signature: "setResult(uint256,uint256)",
        params: [
          { name: "agendaId", type: "uint256", description: "ID of the agenda" },
          { name: "result", type: "uint256", description: "Result value (0=PENDING, 1=ACCEPT, 2=REJECT)" },
        ],
        description: "Directly sets the result of an agenda. Can override vote outcomes.",
        example: "Override the result of agenda #42 to ACCEPT",
        risk: "dangerous",
      },
      {
        name: "setStatus",
        signature: "setStatus(uint256,uint256)",
        params: [
          { name: "agendaId", type: "uint256", description: "ID of the agenda" },
          { name: "status", type: "uint256", description: "New status value" },
        ],
        description: "Directly sets the status of an agenda, overriding the normal lifecycle.",
        example: "Override the status of agenda #42",
        risk: "dangerous",
      },
    ],
  },

  // ─── DepositManager ─────────────────────────────────────────────
  {
    name: "DepositManager",
    address: "0x0b58ca72b12f01fc05f8f252e226f3e2089bd00e",
    category: "staking",
    description: "Manages WTON deposits and withdrawals for Layer2 staking.",
    functions: [
      {
        name: "setMinDepositGasLimit",
        signature: "setMinDepositGasLimit(uint32)",
        params: [{ name: "gasLimit", type: "uint32", description: "Minimum gas limit for deposit transactions" }],
        description: "Sets the minimum gas limit required for deposit transactions.",
        example: "Set the minimum deposit gas limit to 200000",
        risk: "safe",
      },
      {
        name: "setAddresses",
        signature: "setAddresses(address,address)",
        params: [
          { name: "l1BridgeRegistry", type: "address", description: "L1BridgeRegistry contract address" },
          { name: "layer2Manager", type: "address", description: "Layer2Manager contract address" },
        ],
        description: "Initializes L1BridgeRegistry and Layer2Manager addresses. Can only be called once.",
        example: "Initialize DepositManager addresses (one-time only)",
        risk: "caution",
        notes: "One-time initialization; reverts if already called",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on DepositManager.",
        example: "Add an admin to DepositManager",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Due to renounceRole pattern, can only remove self.",
        example: "Remove the DAO's own admin role on DepositManager",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on DepositManager to another address",
        risk: "dangerous",
      },
    ],
  },

  // ─── Layer2Manager ──────────────────────────────────────────────
  {
    name: "Layer2Manager",
    address: "0xD6Bf6B2b7553c8064Ba763AD6989829060FdFC1D",
    category: "staking",
    description: "Manages Layer2 operator registration, deposit requirements, and operator manager factories.",
    functions: [
      {
        name: "setMinimumInitialDepositAmount",
        signature: "setMinimumInitialDepositAmount(uint256)",
        params: [{ name: "amount", type: "uint256", description: "Minimum initial deposit in WTON ray" }],
        description: "Sets the minimum amount operators must deposit when registering a new Layer2.",
        example: "Set the minimum initial deposit for Layer2 registration to 1000 WTON",
        risk: "safe",
      },
      {
        name: "setOperatorManagerFactory",
        signature: "setOperatorManagerFactory(address)",
        params: [{ name: "factory", type: "address", description: "New OperatorManagerFactory address" }],
        description: "Sets the factory contract used to create operator manager instances.",
        example: "Set the operator manager factory address on Layer2Manager",
        risk: "caution",
      },
      {
        name: "setAddresses",
        signature: "setAddresses(address,address,address,address,address,address,address,address)",
        params: [
          { name: "l1BridgeRegistry", type: "address", description: "L1BridgeRegistry" },
          { name: "depositManager", type: "address", description: "DepositManager" },
          { name: "seigManager", type: "address", description: "SeigManager" },
          { name: "ton", type: "address", description: "TON token" },
          { name: "wton", type: "address", description: "WTON token" },
          { name: "dao", type: "address", description: "DAO address" },
          { name: "layer2Registry", type: "address", description: "Layer2Registry" },
          { name: "candidateFactory", type: "address", description: "CandidateFactory" },
        ],
        description: "Initializes all dependent contract addresses. One-time initialization.",
        example: "Initialize Layer2Manager addresses (one-time only)",
        risk: "caution",
        notes: "One-time initialization; reverts if already called",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on Layer2Manager.",
        example: "Add an admin to Layer2Manager",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Unlike renounceRole contracts, Layer2Manager allows removing other admins.",
        example: "Remove an admin from Layer2Manager",
        risk: "caution",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on Layer2Manager to another address",
        risk: "dangerous",
      },
    ],
  },

  // ─── Layer2Registry ─────────────────────────────────────────────
  {
    name: "Layer2Registry",
    address: "0x7846c2248a7b4de77e9c2bae7fbb93bfc286837b",
    category: "registry",
    description: "Registry of Layer2 operators eligible for seigniorage. Controls registration, minter, and operator roles.",
    functions: [
      {
        name: "unregister",
        signature: "unregister(address)",
        params: [{ name: "layer2", type: "address", description: "Layer2 contract address to unregister" }],
        description: "Unregisters a Layer2 operator, removing their seigniorage eligibility.",
        example: "Unregister a Layer2 operator from the registry",
        risk: "dangerous",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on Layer2Registry.",
        example: "Add an admin to Layer2Registry",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Due to renounceRole pattern, can only remove self.",
        example: "Remove the DAO's own admin role on Layer2Registry",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on Layer2Registry to another address",
        risk: "dangerous",
      },
      {
        name: "addMinter",
        signature: "addMinter(address)",
        params: [{ name: "account", type: "address", description: "Address to grant minter role" }],
        description: "Grants the minter role on Layer2Registry.",
        example: "Add a minter to Layer2Registry",
        risk: "caution",
      },
      {
        name: "removeMinter",
        signature: "removeMinter(address)",
        params: [{ name: "account", type: "address", description: "Address to remove minter role from" }],
        description: "Removes the minter role on Layer2Registry.",
        example: "Remove a minter from Layer2Registry",
        risk: "caution",
      },
      {
        name: "addOperator",
        signature: "addOperator(address)",
        params: [{ name: "account", type: "address", description: "Address to grant operator role" }],
        description: "Grants the operator role on Layer2Registry.",
        example: "Add an operator to Layer2Registry",
        risk: "caution",
      },
      {
        name: "removeOperator",
        signature: "removeOperator(address)",
        params: [{ name: "account", type: "address", description: "Address to remove operator role from" }],
        description: "Removes the operator role on Layer2Registry.",
        example: "Remove an operator from Layer2Registry",
        risk: "caution",
      },
    ],
  },

  // ─── L1BridgeRegistry ──────────────────────────────────────────
  {
    name: "L1BridgeRegistry",
    address: "0x39d43281A4A5e922AB0DCf89825D73273D8C5BA4",
    category: "registry",
    description: "Registry for L1 bridge rollups. Controls seigniorage add-on participation, manager/registrant roles.",
    functions: [
      {
        name: "setSeigniorageCommittee",
        signature: "setSeigniorageCommittee(address)",
        params: [{ name: "committee", type: "address", description: "New seigniorage committee address" }],
        description: "Sets the address authorized to approve/reject seigniorage add-on participation.",
        example: "Set the seigniorage committee address on L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "rejectCandidateAddOn",
        signature: "rejectCandidateAddOn(address)",
        params: [{ name: "rollup", type: "address", description: "Rollup address to reject" }],
        description: "Rejects a rollup's seigniorage add-on application. Requires onlySeigniorageCommittee.",
        example: "Reject a rollup's seigniorage add-on candidacy",
        risk: "caution",
      },
      {
        name: "restoreCandidateAddOn",
        signature: "restoreCandidateAddOn(address,bool)",
        params: [
          { name: "rollup", type: "address", description: "Rollup address to restore" },
          { name: "flag", type: "bool", description: "Restore mode flag" },
        ],
        description: "Restores a previously rejected rollup's seigniorage add-on candidacy.",
        example: "Restore a rejected rollup's seigniorage add-on candidacy",
        risk: "caution",
      },
      {
        name: "setAddresses",
        signature: "setAddresses(address,address,address)",
        params: [
          { name: "addr1", type: "address", description: "First initialization address" },
          { name: "addr2", type: "address", description: "Second initialization address" },
          { name: "addr3", type: "address", description: "Third initialization address" },
        ],
        description: "Initializes dependent contract addresses. One-time initialization.",
        example: "Initialize L1BridgeRegistry addresses (one-time only)",
        risk: "caution",
        notes: "One-time initialization; reverts if already called",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on L1BridgeRegistry.",
        example: "Add an admin to L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Unlike renounceRole contracts, can remove other admins.",
        example: "Remove an admin from L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on L1BridgeRegistry to another address",
        risk: "dangerous",
      },
      {
        name: "addManager",
        signature: "addManager(address)",
        params: [{ name: "account", type: "address", description: "Address to grant manager role" }],
        description: "Grants the manager role on L1BridgeRegistry.",
        example: "Add a manager to L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "removeManager",
        signature: "removeManager(address)",
        params: [{ name: "account", type: "address", description: "Address to remove manager role from" }],
        description: "Removes the manager role from an address.",
        example: "Remove a manager from L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "revokeManager",
        signature: "revokeManager(address)",
        params: [{ name: "account", type: "address", description: "Address whose manager role is revoked" }],
        description: "Revokes the manager role (alternate method).",
        example: "Revoke a manager's role on L1BridgeRegistry",
        risk: "caution",
      },
      {
        name: "revokeRegistrant",
        signature: "revokeRegistrant(address)",
        params: [{ name: "account", type: "address", description: "Address whose registrant role is revoked" }],
        description: "Revokes the registrant role. Only callable by owner.",
        example: "Revoke a registrant's role on L1BridgeRegistry",
        risk: "caution",
      },
    ],
  },

  // ─── CandidateFactory ──────────────────────────────────────────
  {
    name: "CandidateFactory",
    address: "0x9fc7100a16407ee24a79c834a56e6eca555a5d7c",
    category: "registry",
    description: "Factory contract for creating governance candidate contracts.",
    functions: [
      {
        name: "setAddress",
        signature: "setAddress(address,address,address,address,address)",
        params: [
          { name: "depositManager", type: "address", description: "DepositManager address" },
          { name: "committee", type: "address", description: "DAOCommittee address" },
          { name: "candidateImplementation", type: "address", description: "Candidate logic implementation" },
          { name: "ton", type: "address", description: "TON token address" },
          { name: "wton", type: "address", description: "WTON token address" },
        ],
        description: "Sets all dependent contract addresses on CandidateFactory.",
        example: "Set addresses on CandidateFactory",
        risk: "caution",
        notes: "May revert if values match current (same-value check)",
      },
      {
        name: "addAdmin",
        signature: "addAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to grant admin role" }],
        description: "Grants the admin role on CandidateFactory.",
        example: "Add an admin to CandidateFactory",
        risk: "caution",
      },
      {
        name: "removeAdmin",
        signature: "removeAdmin(address)",
        params: [{ name: "account", type: "address", description: "Address to remove admin role from" }],
        description: "Removes the admin role. Due to renounceRole pattern, can only remove self.",
        example: "Remove the DAO's own admin role on CandidateFactory",
        risk: "caution",
        notes: "OZ AccessControl: can only remove msg.sender's own role",
      },
      {
        name: "transferAdmin",
        signature: "transferAdmin(address)",
        params: [{ name: "newAdmin", type: "address", description: "Address to receive admin role" }],
        description: "Adds newAdmin as admin and removes the caller's own admin role.",
        example: "Transfer the DAO's admin role on CandidateFactory to another address",
        risk: "dangerous",
      },
    ],
  },

  // ─── TON ────────────────────────────────────────────────────────
  {
    name: "TON",
    address: "0x2be5e8c109e2197D077D13A82dAead6a9b3433C5",
    category: "token",
    description: "Tokamak Network native token (18 decimals). Has a SeigToken restriction on transferFrom.",
    functions: [
      {
        name: "approve",
        signature: "approve(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address to approve" },
          { name: "amount", type: "uint256", description: "Amount in TON wei" },
        ],
        description: "Approves a spender to transfer TON from the DAO's balance.",
        example: "Approve a spender to spend TON from the DAO",
        risk: "caution",
      },
      {
        name: "approveAndCall",
        signature: "approveAndCall(address,uint256,bytes)",
        params: [
          { name: "spender", type: "address", description: "Address to approve and call" },
          { name: "amount", type: "uint256", description: "Amount in TON wei" },
          { name: "data", type: "bytes", description: "Extra data passed to onApprove callback" },
        ],
        description: "Approves a spender and triggers the onApprove callback. Used for TON-to-WTON swaps.",
        example: "Swap TON to WTON using approveAndCall on the TON contract",
        risk: "caution",
      },
      {
        name: "transfer",
        signature: "transfer(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount in TON wei" },
        ],
        description: "Transfers TON from the DAO to a recipient.",
        example: "Transfer TON from the DAO to a recipient address",
        risk: "dangerous",
      },
      {
        name: "transferFrom",
        signature: "transferFrom(address,address,uint256)",
        params: [
          { name: "sender", type: "address", description: "Source address" },
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount in TON wei" },
        ],
        description: "Transfers TON on behalf of sender. SeigToken restriction: msg.sender must equal sender or recipient.",
        example: "Transfer TON from the DAO using transferFrom",
        risk: "dangerous",
        notes: "SeigToken restriction: msg.sender must be sender or recipient; third-party calls revert",
      },
    ],
  },

  // ─── WTON ───────────────────────────────────────────────────────
  {
    name: "WTON",
    address: "0xc4A11aaf6ea915Ed7Ac194161d2fC9384F15bff2",
    category: "token",
    description: "Wrapped TON (27 decimals, ray). Standard ERC20 without SeigToken restriction. Supports swap operations.",
    functions: [
      {
        name: "swapToTON",
        signature: "swapToTON(uint256)",
        params: [{ name: "wtonAmount", type: "uint256", description: "Amount of WTON in ray (27 decimals)" }],
        description: "Burns WTON and mints equivalent TON (1 WTON ray = 1 TON wei).",
        example: "Swap 100 WTON to TON",
        risk: "safe",
      },
      {
        name: "swapFromTON",
        signature: "swapFromTON(uint256)",
        params: [{ name: "tonAmount", type: "uint256", description: "Amount of TON in wei (18 decimals)" }],
        description: "Burns TON (requires prior approve) and mints equivalent WTON.",
        example: "Swap 100 TON to WTON",
        risk: "safe",
      },
      {
        name: "decreaseAllowance",
        signature: "decreaseAllowance(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address whose allowance is reduced" },
          { name: "subtractedValue", type: "uint256", description: "Amount to subtract in WTON ray" },
        ],
        description: "Decreases the WTON spending allowance for a spender.",
        example: "Decrease WTON allowance for a spender by 500 WTON",
        risk: "safe",
      },
      {
        name: "increaseAllowance",
        signature: "increaseAllowance(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address whose allowance is increased" },
          { name: "addedValue", type: "uint256", description: "Amount to add in WTON ray" },
        ],
        description: "Increases the WTON spending allowance for a spender.",
        example: "Increase WTON allowance for a spender by 500 WTON",
        risk: "safe",
      },
      {
        name: "swapToTONAndTransfer",
        signature: "swapToTONAndTransfer(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Address to receive TON" },
          { name: "wtonAmount", type: "uint256", description: "Amount of WTON in ray" },
        ],
        description: "Burns WTON and sends the resulting TON to a specified recipient.",
        example: "Swap WTON to TON and send to a recipient",
        risk: "caution",
      },
      {
        name: "swapFromTONAndTransfer",
        signature: "swapFromTONAndTransfer(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Address to receive WTON" },
          { name: "tonAmount", type: "uint256", description: "Amount of TON in wei" },
        ],
        description: "Burns TON (requires prior approve) and sends the resulting WTON to a recipient.",
        example: "Swap TON to WTON and send to a recipient",
        risk: "caution",
      },
      {
        name: "approve",
        signature: "approve(address,uint256)",
        params: [
          { name: "spender", type: "address", description: "Address to approve" },
          { name: "amount", type: "uint256", description: "Amount in WTON ray" },
        ],
        description: "Approves a spender to transfer WTON from the DAO's balance.",
        example: "Approve a spender to spend WTON from the DAO",
        risk: "caution",
      },
      {
        name: "approveAndCall",
        signature: "approveAndCall(address,uint256,bytes)",
        params: [
          { name: "spender", type: "address", description: "Address to approve and call" },
          { name: "amount", type: "uint256", description: "Amount in WTON ray" },
          { name: "data", type: "bytes", description: "Extra data for onApprove callback" },
        ],
        description: "Approves a spender and triggers the onApprove callback.",
        example: "Use WTON approveAndCall to deposit into a staking contract",
        risk: "caution",
      },
      {
        name: "transfer",
        signature: "transfer(address,uint256)",
        params: [
          { name: "recipient", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount in WTON ray" },
        ],
        description: "Transfers WTON from the DAO to a recipient. Standard ERC20 transfer.",
        example: "Transfer WTON from the DAO to a recipient address",
        risk: "dangerous",
      },
      {
        name: "transferFrom",
        signature: "transferFrom(address,address,uint256)",
        params: [
          { name: "from", type: "address", description: "Source address" },
          { name: "to", type: "address", description: "Destination address" },
          { name: "amount", type: "uint256", description: "Amount in WTON ray" },
        ],
        description: "Transfers WTON on behalf of another address. Standard ERC20 transferFrom (no SeigToken restriction).",
        example: "Transfer WTON from the DAO using transferFrom",
        risk: "dangerous",
      },
      {
        name: "addMinter",
        signature: "addMinter(address)",
        params: [{ name: "account", type: "address", description: "Address to grant minter role" }],
        description: "Grants the minter role on WTON. Requires caller to already be a minter.",
        example: "Add a minter to the WTON contract",
        risk: "dangerous",
        notes: "DAO may not have minter role on WTON; call may revert",
      },
      {
        name: "transferOwnership",
        signature: "transferOwnership(address)",
        params: [{ name: "newOwner", type: "address", description: "New owner address" }],
        description: "Transfers ownership of the WTON contract. DAO is typically NOT the direct owner.",
        example: "Transfer ownership of the WTON contract",
        risk: "dangerous",
        notes: "DAO is typically not the WTON owner (SeigManager is); call may revert",
      },
    ],
  },
];
